# Rule to build the main program
1-2thread : 1-2thread.o
	gcc 1-2thread.o -o 1-2thread -lpthread

# Sources compilation
1-2thread.o : 1-2thread.c
	gcc -c 1-2thread.c

# Clean
clean :
	rm -f 1-2thread.o
